Set up cron jobs
xusandrew/cs-348-project pull request #98
Opened 2024-07-21 18:36 UTC by mxc-maggiechen

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/react-email-starter/emails/newsletterTemplate.tsx
this is for preview of the email template

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/src/app/api/newsletter/route.ts
this is the cron job script for newsletter, not finished since newsletter functions and tables are not implemented yet

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/src/app/api/rsvp-reminder/route.ts
this is the cron job script for rsvp reminders

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/src/app/email/mailOptions.tsx
file for email sending

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/src/app/email/templates/NewsletterEmail.tsx
newsletter email template

2024-07-22 17:13 UTC, mxc-maggiechen commented on frontend/src/app/email/templates/RsvpReminderEmail.tsx
rsvp reminder email template

2024-07-22 17:13 UTC, mxc-maggiechen commented on vercel.json
sets up cron job on vercel

2024-07-23 21:33 UTC, xusandrew requested changes

2024-07-23 21:33 UTC, xusandrew commented on vercel.json
> +            "schedule": "0 2 * * 1"
this is how cron jobs work on vercel? very cool

2024-07-23 21:33 UTC, xusandrew commented on frontend/src/lib/actions.ts
this files code should be in src/lib/rvsp.ts cus i remember moving it there, you can delete this file and import from the other one

2024-07-23 21:33 UTC, xusandrew commented on frontend/src/app/email/mailOptions.tsx
can you move all the files in src/app/email to a seperate folder? right now, if we deploy this a radom user could go to the url 

url/email/templates/{template} and see our code

2024-07-23 21:33 UTC, xusandrew commented on frontend/src/app/email/mailOptions.tsx
you can move it to src/lib/emails and put all the files in there. Keep the api routes though

2024-07-24 22:55 UTC, xusandrew approved these changes
looks good

2024-07-24 23:54 UTC, merged